### ISSUE TITLE
Ability to validate tuts in README.md

### ISSUE THREAD

**Issue by joprice** [tpolecat/tut#90] opened 2016-01-07 18:17 UTC
I know the main intent of tut is to produce separate html files, but I think it would be useful to have an option to validate any tuts (or scala blocks) found in static readme files, since this is probably the most common use case of unmaintained examples.

**Comment by tpolecat** [comment] 2016-01-07 18:19
Yep, thanks! This has been requested before and is on the list.

Duplicate of #59

**Closed by tpolecat** 2016-01-07 18:19 UTC
